version: '2.1'
orbs:
  shellcheck: circleci/shellcheck@2.0.0
jobs:
  my_job:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - shellcheck/install
      - run:
          command: find . -type f -name '*.sh' | xargs shellcheck --external-sources
          name: Run Shellcheck command
